### ISSUE TITLE
Some Questions!!

### ISSUE THREAD

**Issue by AliAryanTech** [salman0ansari/Tg2Wa#3]
What's KEY? (Invitation key) there's no description?.....

Is this multi device supported.? Coz it's using Baileys?

**Comment by salman0ansari** [comment]
only people with key can start bot
Yes

**Comment by AliAryanTech** [comment]
> only people with key can start bot Yes

It should be author people ID
And if it's multi device supported then how to connect bot with WhatsApp?

And if you want to convert tgs to webp **animated** **stickers** then try - [This](https://github.com/eltiempoes/python-lottie)

**Comment by salman0ansari** [comment]
> 
huh?
to connect whatsapp run `node bot.js` you will see qrcode in your terminal scan it and you done

**Comment by AliAryanTech** [comment]
> > 
> 
> huh? to connect whatsapp run `node bot.js` you will see qrcode in your terminal scan it and you done

It's inbuilt? Like [Chitoge](https://github.com/ShineiIchijo/Chitoge)

Can I run it on termux?

**Comment by salman0ansari** [comment]
> > > 
> > 
> > 
> > huh? to connect whatsapp run `node bot.js` you will see qrcode in your terminal scan it and you done
> 
> It's inbuilt? Like [Chitoge](https://github.com/ShineiIchijo/Chitoge)
> 
> Can I run it on termux?

haven't tried on termux let me know if it works

**Comment by AliAryanTech** [comment]
> > > > 
> > > 
> > > 
> > > huh? to connect whatsapp run `node bot.js` you will see qrcode in your terminal scan it and you done
> > 
> > 
> > It's inbuilt? Like [Chitoge](https://github.com/ShineiIchijo/Chitoge)
> > Can I run it on termux?
> 
> haven't tried on termux let me know if it works

Ok inform me please.... And if your bot is running can I see it like how it works? If you don't have any problem.

**Comment by AliAryanTech** [comment]
No reply yet......

**Comment by salman0ansari** [comment]
> No reply yet......

msg me on tg @salman0ansari

**Comment by AliAryanTech** [comment]
> > No reply yet......
> 
> msg me on tg @salman0ansari

Ok let me take risk 😂
